version: "3"

services:
  podcast-sync-service:
    image: ghcr.io/tomhense/podcast-sync-service:master
    container_name: podcast-sync-service
    restart: unless-stopped
    volumes:
      - "data:/usr/src/app/db"
volumes:
  data:
